import type {Metadata} from 'next'
import {ReactNode} from 'react'
import {poppins, raleway, roboto} from '@/app/fonts'
import './global.css'

export const metadata: Metadata = {
   title: 'Nazar Prytuliak',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: ReactNode
}>) {
   return (
      <html lang='en' className={`${raleway.variable} ${roboto.variable} ${poppins.variable}`}>
         <body>{children}</body>
      </html>
   )
}
