import type {Metadata} from 'next'
import {ReactNode} from 'react'
import {navFont, defaultFont, headingFont} from '@/styles/fonts'
import '@/styles/main.scss'

export const metadata: Metadata = {
   title: 'Nazar Prytuliak',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: ReactNode
}>) {
   return (
      <html lang='en' className={`${navFont.variable} ${defaultFont.variable} ${headingFont.variable}`}>
         <body>{children}</body>
      </html>
   )
}
