import type {Metadata} from 'next'
import {ReactNode} from 'react'
import {navFont, defaultFont, headingFont} from '@/styles/fonts'

import '@/styles/main.scss'
import {Providers} from '@/context/Providers'
import {Favicons} from '@/shared/Favicons'

export const metadata: Metadata = {
   title: 'Nazar Prytuliak',
   description: 'Generated by create next app',
   ...Favicons,
}
type Props = {
   children: ReactNode
   params: {
      locale: string
   }
}
export default async function RootLayout({children, params: {locale}}: Props) {
   return (
      <html
         suppressHydrationWarning
         lang={locale}
         className={`${navFont.variable} ${defaultFont.variable} ${headingFont.variable}`}
      >
         <body>
            <Providers>{children}</Providers>
         </body>
      </html>
   )
}
