import type {Metadata} from 'next'
import {ReactNode} from 'react'
import {navFont, defaultFont, headingFont} from '@/styles/fonts'
import {NextIntlClientProvider} from 'next-intl'
import {getMessages} from 'next-intl/server'
import dynamic from 'next/dynamic'
import {cookies} from 'next/headers'
import '@/styles/main.scss'

const AppThemeProvider = dynamic(() => import('@/context/theme'), {
   ssr: true,
})

export const metadata: Metadata = {
   title: 'Nazar Prytuliak',
   description: 'Generated by create next app',
}
interface RootLayoutProps {
   children: ReactNode
   params: {
      locale: string
   }
}
export default async function RootLayout({children, params: {locale}}: RootLayoutProps) {
   const theme = cookies().get('__theme__')?.value || 'system'
   const messages = await getMessages()
   return (
      <html
         suppressHydrationWarning
         lang={locale}
         className={`${theme} ${navFont.variable} ${defaultFont.variable} ${headingFont.variable}`}
      >
         <body>
            <AppThemeProvider defaultTheme={theme} enableColorScheme themes={['light', 'dark', 'system']}>
               <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
            </AppThemeProvider>
         </body>
      </html>
   )
}
